feature/implement-connection-screen
polubis/ProjectManagementApp pull request #137
Opened 2020-11-03 12:24 UTC by Czaroos

- Added connect with github popup when logged user isn't already connected to github.
- It appears every time new session is created.
- Added removeCookie() to CookiesProvider

2020-11-03 13:39 UTC, ajronn approved these changes

2020-11-03 13:39 UTC, ajronn commented on src/core/cookies/CookiesProvider.tsx
> +
Remove space

2020-11-03 17:39 UTC, polubis requested changes

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +interface State {
Please change this to simple flag and state to status and setStatus - object is not needed here

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +const NAME = 'github-connection';
Can be 1 lined with array syntax [NAME, NOT_NOW_VALUE] = [''. '']

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +  const connect = useCallback(() => {
handleConnect convention

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +  const clearCookies = useCallback(() => {
handleClearCookies

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +  const notNow = useCallback(() => {
handleNotNow

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +    shouldShowScreen && (
This should be shouldShowScreen ? content : null;

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +  const shouldShowScreen =
visible will be enough for this variable name

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +  const shouldShowScreen =
can be simplified with user && ((!user.connectedWithGithub && cookies[NAME] !== NOT_NOW_VALUE) || cookies[NAME] === user.id && success) -

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +const NOT_NOW_VALUE = 'not now';
Change value to '1' and name of this variable APPROVED

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +            <div className={csx.buttons}>
You can use footer and avoid not needed classNames - this also increases markdown readability

2020-11-03 17:39 UTC, polubis commented on src/shared/components/github-connect/GithubConnect.tsx
> +        {!success ? (
Remove negation before success and swap contents

2020-11-03 17:39 UTC, polubis commented on src/modules/main/Main.tsx
> +    <GithubConnect />
Add this inside Main just after Sidebar - using this in this place tells me GithubConnect needs Provider data to work

2020-11-05 13:03 UTC, i0skar approved these changes

2020-11-13 20:42 UTC, merged