feature/implement-error-boundary
polubis/ProjectManagementApp pull request #139
Opened 2020-11-04 13:12 UTC by Czaroos

Added error boundary wrapper which catches rendering errors and provide fallback for component where error occured. At this moment it's wrapped around the whole app which is not an ideal solution -> on error the fallback will be displayed preventing other components in DOM from loading. [The best option](https://pl.reactjs.org/docs/error-boundaries.html#where-to-place-error-boundaries) would be to wrap around only sensitive components where render errors are likely to occur - so that other components can be loaded into DOM and fallback will be provided only for the exact component where error was thrown. 

For reference & use cases check [documentation](https://pl.reactjs.org/docs/error-boundaries.html)

2020-11-04 16:17 UTC, polubis requested changes
Good work as always - some things to improve

2020-11-04 16:17 UTC, polubis commented on src/_mocks_/index.ts
> +export * from './api';
Remove /api

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +import React, { Component, ErrorInfo, ReactNode } from 'react';
this should be in core directory

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +export namespace ErrorBoundary {
Remove export

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +    hasError: boolean;
errors state property is not needed - errors is used only to track errors not for display on UI - so should be added as class property not state property

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +    errors: []
remove errors

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +
this.errors.push(error) will be enough

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +    const errorExists = this.state.errors
This code is not needed

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +    if (!errorExists) {
This code is not needed

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +          <Link to="/app">
This should return children always - we don't want scenario with blank page - this is just information.

2020-11-04 16:17 UTC, polubis commented on src/shared/error-boundary/ErrorBoundary.tsx
> +          <Link to="/app">
Remove link - user must stay on same screen

2020-11-05 13:06 UTC, i0skar approved these changes

2020-11-05 16:05 UTC, polubis approved these changes

2020-11-05 16:05 UTC, merged