feature/use-scroll-hook
polubis/ProjectManagementApp pull request #97
Opened 2020-10-07 14:57 UTC by Czaroos

Created useScroll hook & added scroll to top behavior after each step in template and register forms. 

To do:
- unit tests

2020-10-08 08:51 UTC, i0skar approved these changes

2020-10-10 13:51 UTC, polubis requested changes

2020-10-10 13:51 UTC, polubis commented on src/utils/hooks/useScroll.ts
> +import { useEffect } from 'react';
Please remove all additional code - only scroll top feature for the browser window is needed here. So all target, option, scrollToTarget should be removed. 
Rename this hook to useScrollReset and change this in all places

2020-10-10 13:52 UTC, polubis requested changes

2020-10-10 13:52 UTC, polubis commented on src/utils/hooks/useScroll.ts
> +  dispatcher: any,
rename dispatcher to trigger this is a little bit confusing. Also add genertic type - any will be problem after merging new es lint rules

2020-10-13 09:51 UTC, polubis approved these changes

2020-10-13 09:52 UTC, merged